name: Pou en touton - Populate

on:
  schedule:
    - cron: '0 0 * * *'
    # ^ This cron expression triggers the action at 00:00 (midnight) every day


jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
        
        - name: Setup Node.js environment
          uses: actions/setup-node@v3.1.1
  
        - name: Start deployment
          run: |
            git clone https://github.com/SavvasStephanides/pou-en-touton.git
            cd pou-en-touton
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            
            npm install
            cd src/modules/data
            node populateGames.js
            cd ../../..

            git add -A
            git commit -m "[🤖 AutomatedJobs] Populate village of the day"
            git push --all -f https://${{ secrets.GH_TOKEN }}@github.com/SavvasStephanides/pou-en-touton.git
            
